Fixed the pipeline issue
DhanushNehru/board pull request #77
Opened 2024-10-09 04:19 UTC by TheCoderAdi

Fixed the pipeline issue

Changes made :
- Added package.json

![image](https://github.com/user-attachments/assets/389e0075-9d9a-4b29-a2da-585704883ce5)

2024-10-09 10:07 UTC, DhanushNehru approved these changes

2024-10-09 10:09 UTC, DhanushNehru requested changes
Hi @TheCoderAdi can you please fix those lint errors as well ?

2024-10-09 10:53 UTC, TheCoderAdi commented
> Hi @TheCoderAdi can you please fix those lint errors as well ?

Okay, I will fix those errors.

2024-10-09 13:08 UTC, TheCoderAdi commented
Hey @DhanushNehru,
I have fixed the linting issues , Review it.

2024-10-10 06:40 UTC, DhanushNehru approved these changes

2024-10-10 06:40 UTC, merged